name: Build executable binarys
on: [push, pull_request]
jobs:
  stack-build:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v2
    -
      uses: actions/setup-haskell@v1
      with:
        enable-stack: true
        stack-version: 'latest'
    -
      uses: actions/cache@v2
      env:
        cache-name: cache-stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./package.yaml', './stack.yaml', './stack.yaml.lock') }}
    -
      name: Build binaries
      run: |
        stack --version
        stack build :asmJsonCpp-exe :asmJsonCpp-server
  nix-flake-build:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v2
    -
      uses: cachix/install-nix-action@v13
      with:
        install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
        install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
        extra_nix_config: |
          experimental-features = nix-command flakes
          substituters = https://cache.nixos.org https://hydra.iohk.io
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
    -
      uses: cachix/cachix-action@v7
      with:
        name: thekk
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    -
      name: Build executables
      run: |
        nix build ".#asmJsonCpp:exe:asmJsonCpp-exe" ".#asmJsonCpp:exe:asmJsonCpp-server"
        nix build
    -
      name: Archive asmJsonCpp-exe binary
      uses: actions/upload-artifact@v2
      with:
        name: asmJsonCpp-exe
        path: result*/**/*
  releasing-tag:
    runs-on: ubuntu-latest
    needs: [nix-flake-build]
    # if: startsWith(github.ref, 'refs/tags/v')
    steps:
    -
      uses: actions/download-artifact@v2
      with:
        name: asmJsonCpp-exe
    -
      name: Taring
      run: |
        cd result
        tar -cavvf ../asmJsonCpp-exe.tar.gz *
    -
      uses: ncipollo/release-action@v1
      with:
        tag: test-release
        allowUpdates: true
        artifacts: asmJsonCpp-exe.tar.gz
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}
